// export default [ "Arizona Diamondbacks",
// "Atlanta Braves",
// "Baltimore Orioles",
// "Boston Red Sox",
// "Chicago Cubs",
// "Chicago White Sox",
// "Cincinnati Reds",
// "Cleveland Indians",
// "Colorado Rockies",
// "Detroit Tigers",
// "Houston Astros",
// "Kansas City Royals",
// "Los Angeles Angels of Anaheim",
// "Los Angeles Dodgers",
// "Miami Marlins",
// "Milwaukee Brewers",
// "Minnesota Twins",
// "New York Mets",
// "New York Yankees",
// "Oakland Athletics",
// "Philadelphia Phillies",
// "Pittsburgh Pirates",
// "San Diego Padres",
// "San Francisco Giants",
// "Seattle Mariners",
// "St.Louis Cardinals",
// "Tampa Bay Rays",
// "Texas Rangers",
// "Toronto Blue Jays",
// "Washington Nationals"]


export default [

  {id: 'Diamondbacks', teamName: 'Arizona Diamondbacks'},
  {id: 'Braves', teamName: 'Atlanta Braves'},
  {id: 'Orioles', teamName: 'Baltimore Orioles'},
  {id: 'Red Sox', teamName: 'Boston Red Sox'},
  {id: 'Cubs', teamName: 'Chicago Cubs'},
  {id: 'White Sox', teamName: 'Chicago White Sox'},
  {id: 'Reds', teamName: 'Cincinnati Reds'},
  {id: 'Indians', teamName: 'Cleveland Indians'},
  {id: 'Rockies', teamName: 'Colorado Rockies'},
  {id: 'Tigers', teamName: 'Detroit Tigers'},
  {id: 'Astros', teamName: 'Houston Astros'},
  {id: 'Royals', teamName: 'Kansas City Royals'},
  {id: 'Angels', teamName: 'LA Angels of Anaheim'},
  {id: 'Dodgers', teamName: 'Los Angeles Dodgers'},
  {id: 'Marlins', teamName: 'Miami Marlins'},
  {id: 'Brewers', teamName: 'Milwaukee Brewers'},
  {id: 'Twins', teamName: 'Minnesota Twins'},
  {id: 'Mets', teamName: 'New York Mets'},
  {id: 'Yankees', teamName: 'New York Yankees'},
  {id: 'Athletics', teamName: 'Oakland Athletics'},
  {id: 'Phillies', teamName: 'Philadelphia Phillies'},
  {id: 'Pirates', teamName: 'Pittsburgh Pirates'},
  {id: 'Padres', teamName: 'San Diego Padres'},
  {id: 'Giants', teamName: 'San Francisco Giants'},
  {id: 'Mariners', teamName: 'Seattle Mariners'},
  {id: 'Cardinals', teamName: 'St. Louis Cardinals'},
  {id: 'Rays', teamName: 'Tampa Bay Rays'},
  {id: 'Rangers', teamName: 'Texas Rangers'},
  {id: 'Blue Jays', teamName: 'Toronto Blue Jays'},
  {id: 'Nationals', teamName: 'Washington Nationals'},
];